<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('Check that one can sign up');
$I->amOnPage('/');
$I->click('//*[@id="nav-menu"]/div/div/div[5]/a');
$I->see("Login in allows you to access and track all your measures in one place.");
// $I->click('//*[@id="pageModal"]/div/div/div[2]/form/div[5]/center/a');
// $I->see('Actually, I have an account.');
// $I->fillField('email', 'mathieu@gmail.com');
// $I->fillField('confirmEmail', 'mathqdieu@gmail.com');
// $I->click('Sign up');
// $I->see('Your email doesn\'t match.');
// $I->fillField('confirmEmail', 'mathieu@gmail.com');
// $I->click('Sign up');
// $I->see('Your password should be at least 6 characters long');
// $I->fillField('password', 'azerty');
// $I->fillField('confirmPassword', 'qwerty');
// $I->click('Sign up');
// $I->see('Your password doesn\'t match.');
// $I->fillField('confirmPassword', 'azerty');
// $I->click('Sign up');
// $I->see('One last thing...');
// $I->click('Sign up');
// $I->seeInDatabase('user', array('email' => 'mathieu@gmail.com'));
// $I->amOnPage('/');
// $I->click('Logout');
// $I->click('//*[@id="nav-menu"]/div/div/div[5]/a');
// $I->click('Sign up here!');
// $I->fillField('email', 'mathieu@gmail.com');
// $I->fillField('password', 'qwerty');
// $I->see('Wrong email and/or password.');
// $I->fillField('password', 'azerty');
// $I->click('Log in ');
// $I->see('My measures');
